version: '3.8'

services:
  scoring_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bati_bank_scoring_service
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_MODEL_URI=models:/xgboost_model/Production
    volumes:
      - ./mlruns:/app/mlruns
    restart: always